### ISSUE TITLE
Need access to this repo's contentful account

### ISSUE THREAD

**Issue by kaleem-elahi** [whitep4nth3r/nextjs-contentful-blog-starter#13]
Hi @whitep4nth3r 

Thanks for creating this repo, I need a little help, Need access to space of contentful of this project

my email is SHAIKH9996@gmail.com

Thanks,
Kaleem

**Comment by whitep4nth3r** [comment]
Do the credentials provided in this file not work? https://github.com/whitep4nth3r/nextjs-contentful-blog-starter/blob/main/.env.local.example

**Comment by kaleem-elahi** [comment]
How to use these files to use contenful Ui for this space account ?

**Comment by whitep4nth3r** [comment]
Full instructions are in the README: https://github.com/whitep4nth3r/nextjs-contentful-blog-starter#readme

**Comment by kaleem-elahi** [comment]
Thanks @whitep4nth3r Got it
