### ISSUE TITLE
How to render video assets (not embeds)

### ISSUE THREAD

**Issue by haschdl** [whitep4nth3r/nextjs-contentful-blog-starter#14]
Thank you for this great project, I learned a lot trying to RichTextPageContent to work! I could not however get a video asset to render in the page - by that I mean a video that is uploaded to Contentful as an Asset, and added as an Entry to a post. It looks like the component assumes that every embedded asset is to be rendered as an image tag, could that be the reason?
https://github.com/whitep4nth3r/nextjs-contentful-blog-starter/blob/3b14f516b9cfd8a7b666d0a02d37626c4a063d53/components/RichTextPageContent/index.js#L166

Did I miss something? The error is that the code is treating the video as an image.

**Comment by whitep4nth3r** [comment]
Yes that's probably the reason!

You can look at the `contentType` of the asset, and render that accordingly.

This might help: https://whitep4nth3r.com/blog/rich-text-field-tips-and-tricks/#rendering-video-assets-not-iframe-embeds-in-rich-text

**Comment by haschdl** [comment]
you have an answer for everything :) 👍  thank you for your prompt reply, I got to a similar solution, but using `react-player` - struggled a bit with styling but it works. thanks again @whitep4nth3r !

**Comment by whitep4nth3r** [comment]
You're welcome, and good luck with the project!
