### ISSUE TITLE
A question to your ContentfulApi

### ISSUE THREAD

**Issue by gutisalex** [whitep4nth3r/nextjs-contentful-blog-starter#15]
First off, nice pair coding with Jason on Youtube! Love the content...

I would like to know in case you have a lot of different api calls to CF, do you still put them into that one file? Or would you split them into different files and scope them a little bit more? I like the way you did it and I was doing it almost the same in a project I am a part of but my Lead Dev was asking me if we scale, if this would be good to put all those calls into a single file?! I think it depends... centralising all API Calls to CF in a single file kinda makes sense! What do you think?

**Comment by whitep4nth3r** [comment]
Hi @gutisalex!

Thanks for your message.

I usually split the API calls out, actually, by _content type_. You can see how I do it in my [current personal website here](https://github.com/whitep4nth3r/mk2-p4nth3rblog/tree/main/lib). Notice how each file is named after the content type it is referencing:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/52798353/218976240-7dd1a205-9d3e-4ff2-adaf-66b217477658.png">

In this starter project I didn't want to be too opinionated, but when files get too big, I usually recommend splitting out the code into a system that makes sense for the project and the developers working on it.

Hope that helps!

(and I really need to update the dependencies on this project, so thanks for the reminder!)

**Comment by gutisalex** [comment]
Thank you for the very quick answer! So splitting them into several files... ya makes sense if they get too big! I am gonna look into this project! Great work! Thanks for sharing... KR
