### ISSUE TITLE
TypeError: links.entries.inline is not iterable

### ISSUE THREAD

**Issue by ghost** [whitep4nth3r/nextjs-contentful-blog-starter#6]
<img width="945" alt="Screenshot 2021-05-28 at 1 08 27 pm" src="https://user-images.githubusercontent.com/78745391/119981758-e6607900-bfb5-11eb-9f0b-bc47439e4ef9.png">
Met with an error when clicking 'see more articles' (http://localhost:3000/blog). Contentful models are duplicates of those provided.

**Comment by whitep4nth3r** [comment]
Hey @rebeccabirkett thanks for that — it will be because you have no inline entries and I didn't account for this.

Let me put a quick fix in and you can fetch upstream.

**Comment by whitep4nth3r** [comment]
@rebeccabirkett I've just pushed a fix, please let me know if that solved your problem!

**Comment by whitep4nth3r** [comment]
p.s. to fetch the latest changes, go to your repository and click the the button above the file list to fetch the latest changes from the origin of the fork!

**Comment by ghost** [comment]
@whitep4nth3r Good fix! Thanks so much! 👍🏻
